### ISSUE TITLE
schemeApps.json in a Framework or downloaded dynamically?

### ISSUE THREAD

**Issue by reliasn** [danielamitay/iHasApp#29]
I want to use iHasApp in a separate framework that will be loaded by the main project. When I include iHasApp files (.m, .h and .json), the library doesn't work because it can't find the schemeApps.json file with this code:
```
NSString *appSchemesDictionaryPath = [selfBundle pathForResource:@"schemeApps" ofType:@"json"];
```

appSchemesDictionaryPath is "nil" when the .JSON is in the Framework. It works correctly when I add the .JSON to the main project, but that's not what I want.

Is there an easy way of doing this, that is, referencing the resource schemeApps.json located in my Framework instead of the main project?

Another solution that I thought of: making schemeApps.json to be downloaded at the start of the app and cache it (to avoid downloading 300kB+ every time). So I would replace:
```
NSData *schemeAppsData = [NSData dataWithContentsOfFile:appSchemesDictionaryPath
                                                            options:NSDataReadingMappedIfSafe
                                                              error:&dataError];
```
with dataWithContentsOfURL, and add some extra verification to see if the file exists or not.

What do you think of these 2 approaches? Any insights are appreciated.

Regards!

**Comment by danielamitay** [comment]
iHasApp used to have a download fallback, but ultimately it was included in a widely distributed framework, and I had to take that resource offline. You can take a look at the code that did so (now removed) here: https://github.com/danielamitay/iHasApp/commit/86d95e07bd5e0d2515bea3106c9be7b642845b0e

As to why finding the json file in your own library does not work, I am unsure. `NSBundle *selfBundle = [NSBundle bundleForClass:[self class]];` should work. It is possible that I overthought this process, and that `[NSBundle mainBundle]` is the correct implementation.

---
As a side note, if your company is relying on iHasApp for app detection, make sure you acknowledge the weakness with storing the file client-side: a stale dataset; and the weakness with storing the file server-side: latency and now you need a way of curating the data. There are solutions to this, but they are beyond the scope of this repository.

**Comment by danielamitay** [comment]
You can also try NSBundle's `-bundleWithIdentifier:`

**Comment by reliasn** [comment]
Couldn't get it to work: tried every single method to access the resource in my Framework and even listed the contents in the bundle's path, but I just couldn't find schemeApps.json. It would work only when schemeApps.json was inside the main project. 

It seems that the solution is this "iOS Universal Framework" (https://github.com/kstenerud/iOS-Universal-Framework) but the funny thing is in their Readme.md:

"With Xcode 6, Apple has added iOS framework support to their build tools, so this repo can at last be retired!

Please use Apple's framework target for all new projects, as it is less hacky and is supported by Apple themselves."

Anyways, I ended up implementing the downloadable solution with caching so that the app doesn't download 330k-ish every time. Had to modify a couple things in iHasApp but it was pretty easy, thanks to the simplicity of your code.

One final question: how do I help you to keep the schemeApps.json updated? Are there instructions somewhere?

Best regards!

**Comment by danielamitay** [comment]
Unfortunately I am not accepting updates to the schemeApps.json. The data curation is the core value proposition of app detection, and everyone has different requirements and needs (should it over-report or under-report?). Furthermore, there is little way for me to verify the authenticity of submitted data.

**Comment by reliasn** [comment]
I downloaded mobileCore's iOS SDK and found a schemeApps.json in their "Resources" folder. The file has 411kB, 12k lines, therefore, bigger than the current version in your repository. Do you think they are using iHasApp and have their own schemeApps.json?

If you wish to download their SDK, I uploaded to my Dropbox: https://dl.dropboxusercontent.com/u/230498559/mobilecore_ios_sdk_0.9.5.zip

So yeah, it seems that they are accessing schemeApps.json locally instead of downloading an updated version or whatever. Not the best solution, but I'm still interested to know how they managed to reference schemeApps.json in the Framework. 

And regarding the 411kB size... what do you think about it? Did they build their own .JSON using yours and added more apps? It would be great if there was some public schemeApps.json that would be kept updated by everyone.

Regards and, once again, thanks for this great framework!

**Comment by danielamitay** [comment]
They are using an old version of the schemeApps.json. You can take a look at an older version here: https://github.com/danielamitay/iHasApp/blob/0f9c7e427b98883c80f5199538db9038d9442027/iHasApp/schemeApps.json The file size and line counts are nearly the same.

Can you shoot me an email to chat about your use case? hello@danielamitay.com
