### ISSUE TITLE
Crash at iHasApp.m line 61

### ISSUE THREAD

**Issue by trungung** [danielamitay/iHasApp#30]
iHasApp.m line 61
__63-[iHasApp detectAppIdsWithIncremental:withSuccess:withFailure:]_block_invoke40

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[12

Please help review and resolve this bug. I has checked and saw your comment: "Unhappy with this implementation".

Best.

**Comment by danielamitay** [comment]
This should have been fixed by https://github.com/danielamitay/iHasApp/commit/324cd2ab1d43c5ab4fe07f92ca9f59af14e70813 back in March. (Although it is also a moot point by now). Sorry for the delay
